export const arrobj=[{image:'https://thumbs.dreamstime.com/b/pacific-sunrise-lanikai-beach-hawaii-11054574.jpg',
             image1:'https://thumbs.dreamstime.com/b/miami-south-beach-sunrise-lifeguard-tower-coastline-colorful-cloud-blue-sky-41052450.jpg',
             image2:'https://thumbs.dreamstime.com/b/kangaroo-family-beach-kangaroos-enjoying-sunset-australian-coast-hopping-unison-wet-sand-shows-their-85280789.jpg',
             image3:'https://thumbs.dreamstime.com/b/happy-family-jumping-beach-together-55325505.jpg',
             image4:'https://thumbs.dreamstime.com/b/sunset-scene-tropical-beach-resort-22951320.jpg',
             category:'beach',
             category1:'Beaches'},
             {image:'https://thumbs.dreamstime.com/b/fuji-mountain-kawaguchiko-lake-sunset-autumn-seasons-yamanachi-japan-160331858.jpg',
              image1:'https://thumbs.dreamstime.com/b/northern-light-aurora-borealis-kirkjufell-iceland-mountains-winter-113380435.jpg',
              image2:'https://thumbs.dreamstime.com/b/scenic-view-moraine-lake-mountain-range-sunset-landscape-canadian-rocky-mountains-49666349.jpg',
              image3:'https://thumbs.dreamstime.com/b/bald-eagle-spreads-wings-soars-high-above-snow-capped-mountains-near-homer-alaska-kenai-peninsula-106701625.jpg',
              image4:'https://thumbs.dreamstime.com/b/young-woman-traveler-alps-mountains-winter-travel-active-lifestyle-concept-young-woman-traveler-alps-mountains-travel-130546060.jpg',   
              category:'mountain',
              category1:'Mountains'},
              {image:'https://thumbs.dreamstime.com/b/birds-prey-young-northern-goshawk-accipiter-gentilis-wildlife-scenery-slovakia-europe-106689144.jpg',
               image1:'https://thumbs.dreamstime.com/b/two-birds-grass-habitat-evening-light-brown-skua-catharacta-antarctica-water-bird-sitting-autumn-grass-norw-75951115.jpg',
               image2:'https://thumbs.dreamstime.com/b/bali-mynah-birds-19173506.jpg',
               image3:'https://thumbs.dreamstime.com/b/wildlife-birds-watching-danube-delta-romania-wild-nature-wildlife-birds-watching-danube-delta-romania-144053420.jpg',
               image4:'https://thumbs.dreamstime.com/b/birds-sparrows-staged-showdown-outstretched-wings-branch-spring-66040586.jpg',
               category:'bird',
               category1:'Birds'},
              { image:'https://thumbs.dreamstime.com/b/kebab-fast-food-dish-22677562.jpg',
                image1:'https://thumbs.dreamstime.com/b/fast-food-2458108.jpg',
                image2:'https://thumbs.dreamstime.com/b/fast-food-menu-big-tasty-hamburger-vegetables-french-fries-tomato-ketchup-cola-drink-33670923.jpg',
                image3:'https://thumbs.dreamstime.com/b/angel-food-cake-18578527.jpg',
                image4:'https://thumbs.dreamstime.com/b/food-shot-3340149.jpg',
                category:'food',
                category1:'Foods'}];